CREATE TABLE GENRE (
    ID INT NOT NULL,
    GENRE_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE MOVIE (
    ID INT PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    RATING FLOAT,
    VOTE INT,
    WATCH_LATER INT, 
    IMG_PATH VARCHAR2(250), 
    YEAR INT
);

CREATE TABLE MOVIE_GENRE (
    MOVIE_ID INT,
    GENRE_ID INT,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID)
);

CREATE TABLE CAST (
    MOVIE_ID INT, 
    ORIGINAL_NAME VARCHAR2(150),
    CAST_NAME VARCHAR2(150),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID)
);